# Generated by Django 4.2.1 on 2023-06-06 18:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_options_alter_chore_chore_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorestatus',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=200, null=True, samples=None),
        ),
    ]
