# Generated by Django 4.2.1 on 2023-06-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_chorestatus_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='chore_category',
        ),
        migrations.DeleteModel(
            name='ChoreCategory',
        ),
    ]
