# Generated by Django 4.2.1 on 2023-06-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_chore_chore_category_delete_chorecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorestatus',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
